<?php
define('BLOCK_MEMBERSHIP_PRICE', 300);
define('TEHSIL_MEMBERSHIP_PRICE', 400);
define('DISTRICT_MEMBERSHIP_PRICE', 500);
define('MANDAL_MEMBERSHIP_PRICE', 600);
define('STATE_MEMBERSHIP_PRICE', 800);
?>